var GAME_LEVELS = [
  ["                                                                                ",
   "                                                          oo                    ",
   "                                                                                ",
   "                  h                             oo                              ",
   "                                                      xx!!xx!!!x       o        ",
   "                             o                        xxxxxxxxxx   x            ",
   "                x!!!x           xxxx    oo      xxx               ! xxxxx       ",
   "               x     x         !                                !!!!!!!!        ",
   "              x       x    o  x                                 x!!!!!!!        ",
   "             x         x     x                                  xxx!!!!!        ",
   "         o  x           x   x                                     xxxxx!!xx b   ",
   "            xxxx     xxxxxxx     o                                    xxxxxxxxxx",
   "  xx      !!!!!x     x!!!!!x                    o                               ",
   "  x      x!!!!!x     x!!!!!x       xxx                                          ",
   "  x      x!!!!!yyyyyyx!!!!!x                  xxxxxx                            ",
   "  x  s               x        xxxxxxx                                           ",
   "  x  @               x p                                                        ",
   "  xxxxxxxxxxxxxx   xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "               x!!!x                                                            ",
   "               xxxxx                                                            ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                               !!!!!!!!                                                           ",
   "                                               !!!!!!!!                                                           ",
   "                                                 !!!!                                                           b ",
   "                                                 !!!!                                                           xx",
   "                      o                          !!!!                                             o   o   o       ",
   "                                                  !!                                                              ",
   "                  xxxxxxxxxxx                     !!                                          xxxxxxxxxxxxxxxxxxxx",
   "    s             x!!!!!!!!!x                     !!           xxxxxxxxxxxxxxxxx              !!!!!!!!!!!!!!!!!!!!",
   "    @                  |                          !!           x  o  |   o     x       h                         |",
   "    xxxxx                                         !!           x                                                  ",
   "    x      xxxxx o                               !!!!          xxx                       xxxxxxxxxxxxxxxxxxxxxxxxx",
   "    x            xxx                             !!!!                                        !!!!!!!!!!!!!!!!!!!!!",
   "    x                 xxx                        !!!!               xxxxxxx                  !!!!!!!!!!!!!!!!!!!!!",
   "    x                                          !!!!!!!!                                      !!!!!!!!!!!!!!!!!!!!!",
   "    x                     x                    !!!!!!!!                                      !!!!!!!!!!!!!!!!!!!!!",
   "    x!!!!!!!!!!!!!!!!!!!!!                     !!!!!!!          xxxxx=         x             !!!!!!!!!!!!!!!!!!!!!",
   "    x!!!!!!!!!!!!!!!!!!!!!               h     !!!!!!!xxxxx     x |  !!!!!                   !!!!!!!!!!!!!!!!!!!!!",
   "    x!!!!!!!!!!!!!!!!!!!!!                                      x    !!!!!                   !!!!!!!!!!!!!!!!!!!!!",
   "    x!!!!!!!!!!!!!!!!!!!!!                                |   xxx    !!!!!   xxxxxxxxxxx     !!!!!!!!!!!!!!!!!!!!!",
   "    x!!!!!!!!!!!!!x!!!!!                 s                  =        !!!!!   x               !!!!!!!!!!!!!!!!!!!!!",
   "    x!!!!!!!!!!!!!x                      x             xxxxxx        !!!!!   x               !!!!!!!!!!!!!!!!!!!!!",
   "    x!!!!!!!!!!!!!x  p                         xxxxxxx               !!!!!   xxxxxxxxxx      !!!!!!!!!!!!!!!!!!!!!",
   "    x!!!!!!!!!!!!!xxxxxxxxxx                   x     x               !!!!!       x x         !!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!o  p   x x         !!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxx xx  o o  xx                     ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                      xx     xx                     ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                        xxxxxxx                      ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                      ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                       ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                  |         h                                                                                 ",
   "      b                                                 |                  |                                  ",
   "      xxxx                xxxxx              xxxxx                                               h            ",
   "     x!!!!x              x!!!!!x=    |      x!!!!!x      h     x!!!!x            x!!!!x                       ",
   "    x  |   x=     h     x   |   x          x   |   x          x   |  x=         x  |   x=        x!!!x        ",
   "   x         x         x         x        x         x =      x        x        x        x       x  |  x       ",
   "  x           x       x           x      x           x      x          x      x          x     x       x      ",
   " x             xxxxxxx             xxxxxx             xxxxxx            xxxxxx            xxxxx         xx!s!!",
   "                                                                                                              ",
   "                                                      xxxxxxxxxxxxxxx                                         ",
   "                                      xxxx            x!!!!!!!!!!!!!!                                         ",
   "                                      x!!!            x!!!!!!!!!!!!!!                                         ",
   "                                     xx!!!            x!!!!!!!!!!!!!!                                         ",
   "                                      x!!!            x!!!!!!!!!!!!!!                         x            xx ",
   "                          xx          x!!!=           x!!!!!!!!!!!!!!                                         ",
   "                                      x!!!            x!!!!!!!!!!!!!!         x                               ",
   "                                 x    x!!!            x!!!!!!!!!!!!!!       x!!!x                             ",
   "                             hhhhh  !!x!!!            x!!!!!!!!!!!!!!       !!!!!                             ",
   "                                      x!!!            x!!!!!!!!!!!!!!       !!!!!                             ",
   "                                    xxxxxxxx          x!!!!!!!!!!!!!!        !!!                              ",
   "                            xxxxxxxxxxxxxxxx          x!!!!!!!!!!!!!!         !                 xx            ",
   "                                          xx          x!!!!!!!!!!!!!!                                         ",
   "                     s                    xx                   |         s                                    ",
   "  xx                 x                    x                              x                               xxxxx",
   "  x                                       x                              x                               x x  ",
   "  x                                       x                              x                                 x  ",
   "  x                                       x                              x  =                              x  ",
   "  x                                       x                              x                                 x  ",
   "  xxxxxxx                          o o    x                     p        x         xxx          p          x  ",
   "  x                  x        x    p      x   x x x x x x     xxxxx     xxx       x!!!x         x          x  ",
   "  x                !!!!!!!!!!!!!!!!xxx!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x      s     x   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x      @  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                             |               "],
  ["                                            =                                 |                       |       ",
   "                           |                                                                                  ",
   "   |                                  |                                                                       ",
   "                              h               xx                                                     b        ",
   "                                    =                  h                                  h         xx        ",
   "                   xx  xxxxxxxxxxx                              |    |                                        ",
   "                   x                                x      x                   =                              ",
   "                   x                  =                                                     xx                ",
   "                                                                       x                                    x ",
   "                      x                        =     h                                                        ",
   "                            |                                                   xx                            ",
   "                                     |        x             =                                                 ",
   "                                                                                                              ",
   "                                           =                                                                  ",
   "             x                                           |                                                    ",
   "                                                                                                              ",
   "                       x           x                                     |                                    ",
   "     =                                   =                                                                    ",
   "                   h                           h                                                              ",
   "                                                                                                              ",
   "                        =                        p         =                                                  ",
   "                                                 x                                                            ",
   "                                                          h             =                                     ",
   "                                                                                                              ",
   "                                                      x                                                       ",
   "  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                                     ",
   "  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                                     ",
   "  x  s      |            |          x             x                                                           ",
   "  x  @                          |   xxxxxxxxx                                                                 ",
   "  xxxxxxx      |                              xxxxx                                                           ",
   "        x          |                          x   x                                                           ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  x     x   xxx  x   x  x       x       x  x  xx    x   x                                                     ",
   "   x   x   x   x x   x   x     x x     x      x x   x   x                                                     ",
   "    xxx    x   x x   x    x   x   x   x    x  x  x  x   x                                                     ",
   "     x     x   x x   x     x x     x x     x  x   x x   x                                                     ",
   "     x      xxx  xxxxx      x       x      x  x    xx                                                         ",
   "                                                        x                                                     ",
   "  @                                                                                                           ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
